### PR TITLE
Added linux installer

### PR DESCRIPTION
**Pull request by enderger**
added installer for linux: replaces my other pull request

### CODE REVIEW

**Comment by enderger** [comment]
I need to make a quick edit to the code

**Comment by ProxyNeko** [comment]
Take as long as you need I have a lot to fix on our end

**Comment by enderger** [comment]
k

**Comment by enderger** [comment]
I'll get the pack off of curse and import it to multimc so it can work

**Comment by enderger** [comment]
Can I make a repository for the multiMC instance to clone into the user's folder?

**Comment by enderger** [comment]
Running into file upload speed

**Comment by enderger** [comment]
issues

**Comment by enderger** [comment]
This installer is ready!
I'll just add a README for the installer and it should be good to go!

**Comment by enderger** [comment]
Just fixed the dropbox issue

**Pull request closed without merging**
